import Head from "next/head";
import Header from "./header"
import Footer from "./footer"

export default function LayoutUser({children, userName}) {
      
  return (
    <>
      <Head >
        <title>Dashboard</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/logo.png" />
      </Head>
      <Header userName={userName} />

      <main className="">
        {children}
      </main>
      <Footer />
    </>
  );
}
